DROP TABLE TDFSVE_VEN;
CREATE TABLE TDFSVE_VEN (
    NUM_TIC        INTEGER,
    ID_MAG         INTEGER,
    DAT_HEU_TIC    TIMESTAMP,
    COD_ART        FLOAT,
    COD_CAI        FLOAT,
    MNT_BRU        FLOAT,
    REM_LIN        FLOAT,
    REM_TIC        FLOAT,
    MNT_TTC        FLOAT,
    COD_DEV        VARCHAR(12),
    MNT_TTC_EUR    FLOAT,
    MNT_HT_EUR     FLOAT
);