DROP TABLE C_TDDSVE_PRD;
CREATE TABLE C_TDDSVE_PRD (
    COD_ART     FLOAT,
    LIB_PRD     VARCHAR(160),
    LIB_COL     VARCHAR(84),
    LIB_TAI     VARCHAR(36),
    FAM         VARCHAR(100),
    SS_FAM      VARCHAR(120),
    LIB_GEN     VARCHAR(24),
    CIB_TRN_AGE VARCHAR(44),
    COD_CAT     VARCHAR(12),
    LIB_CAT     VARCHAR(64),
    LIB_MRQ     VARCHAR(104)
);