DROP TABLE EXP_ARTICLE;
CREATE TABLE EXP_ARTICLE (
     COD_MRQ VARCHAR(12),
     LIB_MRQ VARCHAR(104),
     COD_ART FLOAT,
     LIB_PRD VARCHAR(160),
     LIB_COL VARCHAR(84),
     LIB_TAI VARCHAR(36),
     FAM VARCHAR(100),
     SS_FAM VARCHAR(120),
     PRX_VEN FLOAT,
     LIB_GEN VARCHAR(24),
     CIB_TRN_AGE VARCHAR(44),
     COD_CAT VARCHAR(12),
     LIB_CAT VARCHAR(64)
);