CREATE TABLE ARTICLE_exp (
     COD_MRQ VARCHAR(3),
     LIB_MRQ VARCHAR(26),
     COD_ART FLOAT,
     LIB_PRD VARCHAR(40),
     LIB_COL VARCHAR(21),
     LIB_TAI VARCHAR(9),
     FAM VARCHAR(25),
     SS_FAM VARCHAR(30),
     PRX_VEN FLOAT,
     LIB_GEN VARCHAR(6),
     CIB_TRN_AGE VARCHAR(11),
     COD_CAT VARCHAR(3),
     LIB_CAT VARCHAR(16)
);